/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sp4_gouin_maugeais;

/**
 *
 * @author thoma
 */
public class fenetreDeJeu extends javax.swing.JFrame {

    joueur[] listeJoueurs = new joueur[2];
    joueur joueurCourant;
    PlateauDeJeu plateau = new PlateauDeJeu();

    /**
     * Creates new form fenetreDeJeu
     */
    public fenetreDeJeu() {
        initComponents();

        panneau_info_joueurs.setVisible(false); // les 2 panneaux infos joueurs et partie ne sont pas affichés au lancement du programme
        panneau_info_partie.setVisible(false);

        for (int i = 5; i >= 0; i--) {
            for (int j = 0; j < 7; j++) {
                CelluleGraphique cellGraph = new CelluleGraphique(plateau.grille[i][j]); //On récupère la cellule de plateau et on la passe en parametre pour "CelluleGraphique" 

                cellGraph.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        CelluleDeGrille c = cellGraph.celluleAssociee;
                        if (c.jetonCourant == null) {
                            return;
                        }

                        if (c.jetonCourant.couleur.equals(joueurCourant.couleur)) {
                            textemessage.setText("Le joueur " + joueurCourant.Nom() + "récupère un jeton");
                            Jeton jrecup = c.recupererJeton();
                            plateau.tassergrille();
                            joueurCourant.ajouterJeton(jrecup);
                            joueurSuivant();
                        } else {
                            if (joueurCourant.nombreDesintegrateurs > 0) {
                                textemessage.setText("Le joueur " + joueurCourant.Nom() + "desintégre un jeton");
                                c.supprimerJeton();
                                joueurCourant.utiliserDesintegrateur();
                                joueurSuivant();

                            } else {
                                return;
                            }
                        }
                        plateau.tassergrille();
                        panneau_grille.repaint();
                        lbl_j1_desint.setText(listeJoueurs[0].nombreDesintegrateurs + "");
                        lbl_j2_desint.setText(listeJoueurs[1].nombreDesintegrateurs + "");

                        boolean vict_j1 = plateau.GagnantePourCouleur(listeJoueurs[0].couleur);
                        boolean vict_j2 = plateau.GagnantePourCouleur(listeJoueurs[1].couleur);

                        if (vict_j1 && !vict_j2) {
                            textemessage.setText("Victoire de " + listeJoueurs[0].Nom());
                        }
                        if (vict_j2 && !vict_j1) {
                            textemessage.setText("Victoire de " + listeJoueurs[1].Nom());
                        }

                        if (vict_j1 && vict_j2) {
                            if (joueurCourant == listeJoueurs[0]) {
                                textemessage.setText("Victoire de " + listeJoueurs[1].Nom() + " (faute de jeu de l'autre joueur)");
                            } else {
                                textemessage.setText("Victoire de " + listeJoueurs[0].Nom() + " (faute de jeu de l'autre joueur)");
                            }
                        }
                    }
                });

                panneau_grille.add(cellGraph);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nom_joueur2 = new javax.swing.JTextField();
        panneau_grille = new javax.swing.JPanel();
        panneau_creation_partie = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nom_joueur1 = new javax.swing.JTextField();
        btn_start = new javax.swing.JButton();
        Nom_Joueur2 = new javax.swing.JTextField();
        panneau_info_partie = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lbl_jcourant = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        message = new javax.swing.JScrollPane();
        textemessage = new javax.swing.JTextArea();
        panneau_info_joueurs = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_j1_desint = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_j1_nom = new javax.swing.JLabel();
        lbl_j1_couleur = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        lbl_j2_desint = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_j2_nom = new javax.swing.JLabel();
        lbl_j2_couleur = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_col_6 = new javax.swing.JButton();
        btn_col_0 = new javax.swing.JButton();
        btn_col_1 = new javax.swing.JButton();
        btn_col_2 = new javax.swing.JButton();
        btn_col_3 = new javax.swing.JButton();
        btn_col_4 = new javax.swing.JButton();
        btn_col_5 = new javax.swing.JButton();

        Nom_joueur2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nom_joueur2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panneau_grille.setBackground(new java.awt.Color(255, 255, 255));
        panneau_grille.setLayout(new java.awt.GridLayout(6, 7));
        getContentPane().add(panneau_grille, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 672, 576));

        panneau_creation_partie.setBackground(new java.awt.Color(255, 255, 204));
        panneau_creation_partie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nom joueur 2 :");
        panneau_creation_partie.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel2.setText("Nom joueur 1 :");
        panneau_creation_partie.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        panneau_creation_partie.add(Nom_joueur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 120, -1));

        btn_start.setText("Démarrer partie");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        panneau_creation_partie.add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        Nom_Joueur2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nom_Joueur2ActionPerformed(evt);
            }
        });
        panneau_creation_partie.add(Nom_Joueur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 120, -1));

        getContentPane().add(panneau_creation_partie, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 310, 140));

        panneau_info_partie.setBackground(new java.awt.Color(255, 255, 204));
        panneau_info_partie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Infos jeu");
        panneau_info_partie.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lbl_jcourant.setText("joueur courant :");
        panneau_info_partie.add(lbl_jcourant, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        jLabel12.setText("joueur courant :");
        panneau_info_partie.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        textemessage.setColumns(20);
        textemessage.setRows(5);
        message.setViewportView(textemessage);

        panneau_info_partie.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 290, -1));

        getContentPane().add(panneau_info_partie, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, 310, 190));

        panneau_info_joueurs.setBackground(new java.awt.Color(255, 255, 204));
        panneau_info_joueurs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Infos joueurs");
        panneau_info_joueurs.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel4.setText("desintegrateurs:");
        panneau_info_joueurs.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        lbl_j1_desint.setText("nbdesintjoueur1");
        panneau_info_joueurs.add(lbl_j1_desint, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        jLabel6.setText("couleur:");
        panneau_info_joueurs.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel7.setText("joueur 1:");
        panneau_info_joueurs.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        lbl_j1_nom.setText("nomJoueur1");
        panneau_info_joueurs.add(lbl_j1_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        lbl_j1_couleur.setText("couleurjoueur1");
        panneau_info_joueurs.add(lbl_j1_couleur, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));
        panneau_info_joueurs.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 260, 20));

        jLabel5.setText("desintegrateurs:");
        panneau_info_joueurs.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        lbl_j2_desint.setText("nbdesintjoueur2");
        panneau_info_joueurs.add(lbl_j2_desint, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        jLabel8.setText("couleur:");
        panneau_info_joueurs.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        lbl_j2_nom.setText("nomJoueur2");
        panneau_info_joueurs.add(lbl_j2_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        lbl_j2_couleur.setText("couleurjoueur2");
        panneau_info_joueurs.add(lbl_j2_couleur, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        jLabel11.setText("joueur 2:");
        panneau_info_joueurs.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        getContentPane().add(panneau_info_joueurs, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, 310, 260));

        btn_col_6.setText("7");
        btn_col_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col_6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 20, 40, 30));

        btn_col_0.setText("1");
        btn_col_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col_0ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 40, 30));

        btn_col_1.setText("2");
        btn_col_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col_1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 20, 40, 30));

        btn_col_2.setText("3");
        btn_col_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col_2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 20, 40, 30));

        btn_col_3.setText("4");
        btn_col_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col_3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 20, 40, 30));

        btn_col_4.setText("5");
        btn_col_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col_4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 20, 40, 30));

        btn_col_5.setText("6");
        btn_col_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col_5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 40, 30));

        setBounds(0, 0, 1043, 696);
    }// </editor-fold>//GEN-END:initComponents

    private void Nom_joueur2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nom_joueur2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nom_joueur2ActionPerformed

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed

        // TODO add your handling code here:
        panneau_info_joueurs.setVisible(true); // Dès que l'on active le bouton débuter partie, on affiche les deux pannels cachés au début de la partie 
        panneau_info_partie.setVisible(true);
        initialiserPartie();
        panneau_grille.repaint();
        btn_start.setEnabled(false);

    }

    public void creerEtAffecterJeton(joueur j1) {  //méthode qui va créer 30 objets de type Jeton pour chaque couleur et les donnes aux joueurs

        if ("Rouge".equals(j1.getCouleur())) {
            for (int i = 0; i < 31; i++) { //on créer une boucle pour créer les 30 jetons pour le joueur rouge
                Jeton jeton = new Jeton("Rouge");
                j1.ajouterJeton(jeton);
            }
        }

        if ("Jaune".equals(j1.getCouleur())) { //on créer une boucle pour créer les 30 jetons pour le joueur jaune
            for (int i = 0; i < 31; i++) {
                Jeton jeton = new Jeton("Jaune");
                j1.ajouterJeton(jeton);
            }
        }
    }

    public void placerTrousNoirsEtDesintegrateurs() {  //méthode qui va créer 5 trous noirs et désintegrateurs et va cacher certains desintegrateurs derrière des trous noirs
        int i = 0;
        while (i < 2) {
            int x = (int) (Math.random() * (9 - 3)); //on choisi aléatoirement des cases pour placer les trous noirs et desintégrateurs
            int y = (int) (Math.random() * (8 - 3));
            if (plateau.presenceDesintegrateur(x, y) == false) {
                if (plateau.presenceTrouNoir(x, y) == false) {
                    plateau.placerTrouNoir(x, y);
                    plateau.placerDesintegrateur(x, y);

                    i += 1;

                }
            }
        }

        while (i < 5) {  //on répète cette étape jusqu'a ce que le bon nombre de trou noirs et désintégrateurs soit présent
            int x = (int) (Math.random() * (9 - 3));
            int y = (int) (Math.random() * (8 - 3));
            if (plateau.presenceDesintegrateur(x, y) == false) {
                if (plateau.presenceTrouNoir(x, y) == false) {
                    plateau.placerTrouNoir(x, y);
                    i += 1;

                }
            }
        }

        while (i < 8) {

            int x = (int) (Math.random() * (9 - 3));

            int y = (int) (Math.random() * (8 - 3));

            if (plateau.presenceDesintegrateur(x, y) == false) {

                if (plateau.presenceTrouNoir(x, y) == false) {

                    plateau.placerDesintegrateur(x, y);

                    i += 1;

                }

            }

        }

    }

    public void attribuerCouleurAuxJoueurs() {   //méthode permettant de donner une couleur aléatoire aux joueurs entre jaune et rouge

        int valeur = (int) (Math.random() * (2)); //on choisi un chiffre entre 0 et 1

        if (valeur == 0) { //si le chiffre est 0, l'un des joueurs sera rouge et l'autre jaune

            listeJoueurs[0].affecterCouleur("Rouge");

            listeJoueurs[1].affecterCouleur("Jaune");

        } else {  //si le chiffre est 1, l'ordre des couleurs est inversé

            listeJoueurs[0].affecterCouleur("Jaune");

            listeJoueurs[1].affecterCouleur("Rouge");

        }

    }

    public void initialiserPartie() {   //Méthode faisant appels à toutes celles créées dernièrement afin d'initialiser la partie 

        String nomJ1 = Nom_joueur1.getText(); // On a une variable qui prend la valeur rentrée dans le texte field 
        String nomJ2 = Nom_Joueur2.getText();
        
        joueur J1 = new joueur(nomJ1);//Ainsi on crée nos joueurs avec leur nom 
        joueur J2 = new joueur(nomJ2);
        
        listeJoueurs[0] = J1;
        listeJoueurs[1] = J2;

        attribuerCouleurAuxJoueurs();

        lbl_j1_nom.setText(nomJ1);// on remplace les variables affichees par les vrai nom,couleur et nombre datout de jeu pour chaque joueur 
        lbl_j2_nom.setText(nomJ2);
        lbl_j1_couleur.setText(J1.getCouleur());
        lbl_j2_couleur.setText(J2.getCouleur());
        lbl_j1_desint.setText(J1.getNombreDesintegrateurs() + "");
        lbl_j2_desint.setText(J2.getNombreDesintegrateurs() + "");

        

        creerEtAffecterJeton(listeJoueurs[1]);
        creerEtAffecterJeton(listeJoueurs[0]);
        joueurCourant = listeJoueurs[0];
        lbl_jcourant.setText(joueurCourant.Nom()); // Voir le joueur courant
        placerTrousNoirsEtDesintegrateurs();
        plateau.afficherGrilleSurConsole();
        

    }//GEN-LAST:event_btn_startActionPerformed

    private void Nom_Joueur2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nom_Joueur2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nom_Joueur2ActionPerformed

    private void btn_col_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col_0ActionPerformed
        // TODO add your handling code here:
        jouerDansColonne(0);
        if (plateau.colonneRemplie(0) == true) {
            btn_col_0.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_btn_col_0ActionPerformed

    private void btn_col_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col_1ActionPerformed
        // TODO add your handling code here:
        jouerDansColonne(1);
        if (plateau.colonneRemplie(1) == true) {
            btn_col_1.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_btn_col_1ActionPerformed

    private void btn_col_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col_2ActionPerformed
        // TODO add your handling code here:
        jouerDansColonne(2);
        if (plateau.colonneRemplie(2) == true) {
            btn_col_2.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_btn_col_2ActionPerformed

    private void btn_col_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col_3ActionPerformed
        // TODO add your handling code here:
        jouerDansColonne(3);
        if (plateau.colonneRemplie(3) == true) {
            btn_col_3.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_btn_col_3ActionPerformed

    private void btn_col_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col_4ActionPerformed
        // TODO add your handling code here:
        jouerDansColonne(4);
        if (plateau.colonneRemplie(4) == true) {
            btn_col_4.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_btn_col_4ActionPerformed

    private void btn_col_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col_5ActionPerformed
        // TODO add your handling code here:
        jouerDansColonne(5);
        if (plateau.colonneRemplie(5) == true) {
            btn_col_5.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_btn_col_5ActionPerformed

    private void btn_col_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col_6ActionPerformed
        // TODO add your handling code here:
        jouerDansColonne(6);
        if (plateau.colonneRemplie(6) == true) {
            btn_col_6.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_btn_col_6ActionPerformed
    public boolean jouerDansColonne(int indice_colonne) {
        int resultatAction;

        resultatAction = plateau.ajouterJetonDansColonne(joueurCourant.jouerJeton(), indice_colonne);
        if (resultatAction == 12){
            joueurCourant.obtenirDesintegrateur();
        }
        panneau_grille.repaint();

        lbl_j1_desint.setText(listeJoueurs[0].nombreDesintegrateurs + "");
        lbl_j2_desint.setText(listeJoueurs[1].nombreDesintegrateurs + "");

        boolean vict_j1 = plateau.GagnantePourCouleur(listeJoueurs[0].couleur);
        boolean vict_j2 = plateau.GagnantePourCouleur(listeJoueurs[1].couleur);

        if (vict_j1 && !vict_j2) {
            textemessage.setText("Victoire de " + listeJoueurs[0].Nom());
        }
        if (vict_j2 && !vict_j1) {
            textemessage.setText("Victoire de " + listeJoueurs[1].Nom());
        }

        if (vict_j1 && vict_j2) {
            if (joueurCourant == listeJoueurs[0]) {
                textemessage.setText("Victoire de " + listeJoueurs[1].Nom() + " (faute de jeu de l'autre joueur)");
            } else {
                textemessage.setText("Victoire de " + listeJoueurs[0].Nom() + " (faute de jeu de l'autre joueur)");
            }
        }

        if (resultatAction != -1) {
            return false;
        } else {
            return true;
        }
    }

    public void joueurSuivant() {
        if (joueurCourant == listeJoueurs[0]) {
            joueurCourant = listeJoueurs[1];
        } else {
            joueurCourant = listeJoueurs[0];
        }
        lbl_jcourant.setText(joueurCourant.Nom());

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetreDeJeu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nom_Joueur2;
    private javax.swing.JTextField Nom_joueur1;
    private javax.swing.JTextField Nom_joueur2;
    private javax.swing.JButton btn_col_0;
    private javax.swing.JButton btn_col_1;
    private javax.swing.JButton btn_col_2;
    private javax.swing.JButton btn_col_3;
    private javax.swing.JButton btn_col_4;
    private javax.swing.JButton btn_col_5;
    private javax.swing.JButton btn_col_6;
    private javax.swing.JButton btn_start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_j1_couleur;
    private javax.swing.JLabel lbl_j1_desint;
    private javax.swing.JLabel lbl_j1_nom;
    private javax.swing.JLabel lbl_j2_couleur;
    private javax.swing.JLabel lbl_j2_desint;
    private javax.swing.JLabel lbl_j2_nom;
    private javax.swing.JLabel lbl_jcourant;
    private javax.swing.JScrollPane message;
    private javax.swing.JPanel panneau_creation_partie;
    private javax.swing.JPanel panneau_grille;
    private javax.swing.JPanel panneau_info_joueurs;
    private javax.swing.JPanel panneau_info_partie;
    private javax.swing.JTextArea textemessage;
    // End of variables declaration//GEN-END:variables
}
